/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WrappedAddressRouteImport } from './routes/wrapped.$address'
import { Route as DashboardAddressRouteImport } from './routes/dashboard.$address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WrappedAddressRoute = WrappedAddressRouteImport.update({
  id: '/wrapped/$address',
  path: '/wrapped/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAddressRoute = DashboardAddressRouteImport.update({
  id: '/dashboard/$address',
  path: '/dashboard/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/$address': typeof DashboardAddressRoute
  '/wrapped/$address': typeof WrappedAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/$address': typeof DashboardAddressRoute
  '/wrapped/$address': typeof WrappedAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/$address': typeof DashboardAddressRoute
  '/wrapped/$address': typeof WrappedAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard/$address' | '/wrapped/$address'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard/$address' | '/wrapped/$address'
  id: '__root__' | '/' | '/dashboard/$address' | '/wrapped/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardAddressRoute: typeof DashboardAddressRoute
  WrappedAddressRoute: typeof WrappedAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wrapped/$address': {
      id: '/wrapped/$address'
      path: '/wrapped/$address'
      fullPath: '/wrapped/$address'
      preLoaderRoute: typeof WrappedAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$address': {
      id: '/dashboard/$address'
      path: '/dashboard/$address'
      fullPath: '/dashboard/$address'
      preLoaderRoute: typeof DashboardAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardAddressRoute: DashboardAddressRoute,
  WrappedAddressRoute: WrappedAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
